[package]
name = "pristine_internal_api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
colored = "2.0.0"
rand = "0.8.5"
serde = { version = "^1.0.100", features = ["derive"] }
serde_json = "1.0.89"
thiserror = "1.0.38"
