[package]
name = "apeiro_internal_api"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
colored = "2.0.0"
rand = "0.8.5"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = "1.0.38"
