[package]
name = "apeiro_port_mqtt"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
apeiro_engine = { path = "../engine" }
async-trait = "0.1.61"
rumqttc = "0.24.0"
serde = { workspace = true }
serde_json = { workspace = true }
typetag = "0.2.5"
