[package]
name = "pristine_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
better_scoped_tls = "0.1.0"
is-macro = "0.2.1"
once_cell = "1.16.0"
rustc-hash = "1.1.0"
swc = "0.236.10"
swc_atoms = "0.4.29"
swc_common = { version = "0.29.23", features = ["tty-emitter"] }
swc_ecma_ast = "0.95.7"
swc_ecma_codegen = "0.128.13"
swc_ecma_parser = { version = "0.123.11", features = ["typescript"] }
swc_ecma_transforms = "0.199.17"
swc_ecma_transforms_base = "0.112.15"
swc_ecma_utils = "0.106.11"
swc_ecma_visit = "0.81.6"
swc_ecmascript = { version = "0.206.22", features = ["transforms", "visit"] }
tracing = "0.1.37"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }